AllCops:
  Exclude:
    - fixtures/**/*
    - vendor/**/*
  TargetRubyVersion: 2.1

Metrics/LineLength:
  Max: 100

Style/ClassAndModuleChildren:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - '*.gemspec'

Style/SingleLineBlockParams:
  Enabled: false
