source 'https://rubygems.org'

gem 'rspec', '~> 3.5'
# simplecov 0.12.0 has a bug in result merger and the bugfix is not yet released.
# https://github.com/colszowka/simplecov/pull/513
gem 'simplecov', github: 'colszowka/simplecov'
gem 'simplecov-parallel', path: '..'
